name: mat_sjekk
description: "Insekt-, Bovaer- og GMO-varsler for bevisste forbrukere."
publish_to: 'none'
homepage: https://sites.google.com/view/einars-apps/
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Kjernefunksjonalitet
  mobile_scanner: ^5.2.3
  http: ^1.2.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  wakelock_plus: ^1.4.0
  path_provider: ^2.0.14
  intl: ^0.20.2  # For flerspråk
  share_plus: ^12.0.1
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1 # For å lage app-ikon
  build_runner: ^2.4.0
  flutter_gen_runner: ^5.4.0
  hive_test: ^1.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
  
  # L10n - Generate localized strings
  generate: true
